### ISSUE TITLE
Summary Charts: Available Data - data bug

### ISSUE THREAD

**Issue by kcullion** [kids-first/kf-portal-ui#1363]
Explained to @ciaranschutte ... @rosibaj can you confirm that I'm not misinterpreting something?

The available data entries and counts seem to be different than the file repo. There should be more experimental strategies listed for these datatypes. 

For example, in the cohort builder for all data, there's only two rows for "Aligned Reads" and one experimental strategy listed. 
![Screen Shot 2019-03-20 at 12 22 08 PM](https://user-images.githubusercontent.com/18424138/54701290-16c14880-4b0b-11e9-9131-923aa3125804.png)

But in the file repo, there are files for 3 different experimental strategies and the counts aren't consistent.
![Screen Shot 2019-03-20 at 12 22 30 PM](https://user-images.githubusercontent.com/18424138/54701326-2c367280-4b0b-11e9-9a62-45e67aa0c99c.png)

**Comment by rosibaj** [comment]
@kcullion yes, this seems like an issue we should continue to investigate!

**Comment by hlminh2000** [comment]
issue identified and addressed in https://github.com/kids-first/kf-portal-ui/pull/1373

**Comment by kcullion** [comment]
Reopening - needs to also list the other data types like the images and reports (that don't have experimental strategies)

**Comment by kcullion** [comment]
@hlminh2000 the file count links from the cohort builder also don't lead to the same counts on the file repo.

**Comment by rosibaj** [comment]
@hlminh2000 looks like your new query is not grabbing `_missing` bucket on the file.sequencing_experiments.sequencing_strategy   - or is filtering those ones out somehow

**Comment by hlminh2000** [comment]
The file repo file count mismatch is a continuation of this ticket: https://app.zenhub.com/workspaces/oicr-kf-sprints-59a846e9d6fb732a00631122/issues/kids-first/kf-portal-ui/1223

Just including this for reference about the problem.
![](https://files.slack.com/files-pri/T4KJMN4N4-FGTJ386SY/screenshot_20190308-215448.jpg)

For efficiency, I'll address this in here in this ticket.

**Comment by hlminh2000** [comment]
incorrect content of the card is addressed in https://github.com/kids-first/kf-portal-ui/pull/1390

**Comment by kcullion** [comment]
@rosibaj can you check this out again? Sorry, but it still doesn't seem right to me. Like the data types (images and reports) shouldn't have experimental strategies right?

**Comment by rosibaj** [comment]
With the current dataset, this is how the card should look: 
![image](https://user-images.githubusercontent.com/15824252/55020774-edeaf880-4fcd-11e9-8d11-80306514c3c3.png)

**DATA NOTES:**
 there are 184 files with no participants attached. the cohort builder file and participant numbers will `not` match the file repo
